spring:
  #  cloud:
  #    nacos:
  #      discovery:
  #        server-addr: 10.219.192.96:8848
  #        service: ${spring.application.name}
  application:
    name: fizz

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.219.192.96:3306/atlantis?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456

  ### 文件上传
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

mybatis-plus:
  type-aliases-package: com/wjx/osiris/fizz/domain/entity

  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

    #xml文件位置
    mapper-locations: classpath*:mapper/*.xml

    configuration:
      #下划线驼峰转换（mybatis默认false  mybatis-plus默认true）
      map-underscore-to-camel-case: true
      #禁用二级缓存
      cache-enabled: false

    global-config:
      db-config:
        #全局id策略
        id-type: auto
        logic-delete-value: 1
        logic-not-delete-value: 0

### feign
feign:
  httpclient:
    enabled: true
    disable-ssl-validation: true
    max-connections: 300
    max-connections-per-route: 100
    connection-timeout: 3000

  #开启断路器
  circuitbreaker:
    enabled: true

logging:
  file:
    path: /Users/wangjinxin/Documents/logs/osiris/fizz

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://atlantis.com:8080