spring:
  application:
    name: zed
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.address}

  mail:
    host: smtp.163.com #邮箱服务
    username: wjxScott@163.com #邮箱地址
    password: PDIVXWEXEPZWGXDR #邮箱授权码或密码
    properties:
      mail.debug: false
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: true
  boot:
    admin:
      notify:
        mail:
          to: wjxScott@163.com
          from: wjxScott@163.com

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

logging:
  file:
    name: ${logging.path}/${spring.application.name}_info.log

server:
  port: 9000