spring:
  application:
    name: zed
  cloud:
    nacos:
      discovery:
        #        server-addr: { nacos.address }
        server-addr: wangjinxin.cn:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file:
    name: ${logging.path}/${spring.application.name}_info.log

server:
  port: 9000