spring:
  datasource:
    url: jdbc:mysql://wangjinxin.cn:3306/jhin?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    hikari:
      username: root
      password: wjx1415926
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: jhin

#  cloud:
#    nacos:
#      discovery:
#        server-addr: ${nacos_address}

server:
  port: 9011

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

logging:
  file:
    name: ${logging.path}/${spring.application.name}_info.log